<a href="https://colab.research.google.com/github/Skylar-siyu/BigData/blob/main/%E2%80%9CW05_quiz_2026_ipynb%E2%80%9D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 5 Quiz

This notebook contains the SQL Quiz for Week 5. Section 1 uses the New York City data we know and love. Section 2 uses building footprint data from the Google Open Buildings dataset.

INSTRUCTIONS:

Run this notebook in Google Colab. The answer to each quesiton will be a number or a string. Input these into the corresponding question on Moodle. You have 90 minutes to attempt the quiz, so if you get stuck on a question, move on.

Make sure you run all of the cells of code in order, especially the ones that already have code in them! If you run into serious problems, try clicking on the "runtime" tab above and selecting "restart session and run all".
Use the cells below for any necessary setup.

# Section 1

The URL below points to a zip file containing the data on New York City that we've been working with so far.

https://s3.amazonaws.com/s3.cleverelephant.ca/postgis-workshop-2020.zip

## Question 1

Create the following tables using the corresponding shapefiles.
- nyc_neighborhoods
- nyc_census_blocks
- nyc_homicides
- nyc_streets
- nyc_subway_stations

In [1]:
%pip install duckdb leafmap duckdb-engine jupysql lonboard
import duckdb
import leafmap
import pandas as pd
import os
import zipfile
import requests

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)
Collecting leafmap
  Downloading leafmap-0.60.0-py2.py3-none-any.whl.metadata (17 kB)
Collecting duckdb-engine
  Downloading duckdb_engine-0.17.0-py3-none-any.whl.metadata (8.4 kB)
Collecting jupysql
  Downloading jupysql-0.11.1-py3-none-any.whl.metadata (5.9 kB)
Collecting lonboard
  Downloading lonboard-0.13.0-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: anywidget in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.9.21)
Requirement already satisfied: bqplot in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.12.45)
Collecting duckdb
  Downloading duckdb-1.4.4-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: folium in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.20.0)
Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (from leafmap) (5.2.1)
Collecting geojson (from leafmap)
  Downloading geojson-3.2.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (from leafmap) (1.1.2)
Requirement already satisfied: ipyevents in /usr/local/lib/python3.12/dist-packages (from leafmap) (2.0.4)
Requirement already satisfied: ipyfilechooser in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.6.0)
Requirement already satisfied: ipyleaflet in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.20.0)
Collecting ipyvuetify (from leafmap)
  Downloading ipyvuetify-1.11.3-py2.py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/dist-packages (from leafmap) (7.7.1)
Collecting maplibre (from leafmap)
  Downloading maplibre-0.3.6-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from leafmap) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from leafmap) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from leafmap) (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from leafmap) (5.24.1)
Collecting pystac-client (from leafmap)
  Downloading pystac_client-0.9.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: python-box in /usr/local/lib/python3.12/dist-packages (from leafmap) (7.3.2)
Requirement already satisfied: scooby in /usr/local/lib/python3.12/dist-packages (from leafmap) (0.11.0)
Collecting whiteboxgui (from leafmap)
  Downloading whiteboxgui-2.3.0-py2.py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from leafmap) (2025.11.0)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.12/dist-packages (from duckdb-engine) (26.0)
Requirement already satisfied: sqlalchemy>=1.3.22 in /usr/local/lib/python3.12/dist-packages (from duckdb-engine) (2.0.46)
Requirement already satisfied: prettytable>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from jupysql) (3.17.0)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.12/dist-packages (from jupysql) (0.5.5)
Requirement already satisfied: ipython-genutils>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from jupysql) (3.1.6)
Requirement already satisfied: sqlglot>=11.3.7 in /usr/local/lib/python3.12/dist-packages (from jupysql) (25.20.2)
Collecting jupysql-plugin>=0.4.2 (from jupysql)
  Downloading jupysql_plugin-0.4.5-py3-none-any.whl.metadata (7.8 kB)
Collecting ploomber-core>=0.2.7 (from jupysql)
  Downloading ploomber_core-0.2.27-py3-none-any.whl.metadata (532 bytes)
Collecting arro3-compute>=0.4.1 (from lonboard)
  Downloading arro3_compute-0.6.5-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (328 bytes)
Collecting arro3-core>=0.4.1 (from lonboard)
  Downloading arro3_core-0.6.5-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (363 bytes)
Collecting arro3-io>=0.4.1 (from lonboard)
  Downloading arro3_io-0.6.5-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (323 bytes)
Collecting geoarrow-rust-core>=0.5.2 (from lonboard)
  Downloading geoarrow_rust_core-0.6.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (365 bytes)
Requirement already satisfied: pyproj>=3.3 in /usr/local/lib/python3.12/dist-packages (from lonboard) (3.7.2)
Requirement already satisfied: traitlets>=5.7.1 in /usr/local/lib/python3.12/dist-packages (from lonboard) (5.7.1)
Requirement already satisfied: typing-extensions>=4.12.0 in /usr/local/lib/python3.12/dist-packages (from lonboard) (4.15.0)
Requirement already satisfied: psygnal>=0.8.1 in /usr/local/lib/python3.12/dist-packages (from anywidget->leafmap) (0.15.1)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (6.17.1)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (3.6.10)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (7.34.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->leafmap) (3.0.16)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from ploomber-core>=0.2.7->jupysql) (6.0.3)
Collecting posthog>=3.0 (from ploomber-core>=0.2.7->jupysql)
  Downloading posthog-7.8.5-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.12.0->jupysql) (0.5.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyproj>=3.3->lonboard) (2026.1.4)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.3.22->duckdb-engine) (3.3.1)
Requirement already satisfied: traittypes>=0.0.6 in /usr/local/lib/python3.12/dist-packages (from bqplot->leafmap) (0.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->leafmap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->leafmap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->leafmap) (2025.3)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium->leafmap) (0.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium->leafmap) (2.32.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->jupysql) (3.0.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown->leafmap) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown->leafmap) (3.20.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown->leafmap) (4.67.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas->leafmap) (0.12.1)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas->leafmap) (2.1.2)
Requirement already satisfied: jupyter-leaflet<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from ipyleaflet->leafmap) (0.20.0)
Collecting ipyvue<2,>=1.7 (from ipyvuetify->leafmap)
  Downloading ipyvue-1.11.3-py2.py3-none-any.whl.metadata (987 bytes)
Collecting eval-type-backport (from maplibre->leafmap)
  Downloading eval_type_backport-0.3.1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: pydantic>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from maplibre->leafmap) (2.12.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->leafmap) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->leafmap) (9.1.2)
Collecting pystac>=1.10.0 (from pystac[validation]>=1.10.0->pystac-client->leafmap)
  Downloading pystac-1.14.3-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: ipytree in /usr/local/lib/python3.12/dist-packages (from whiteboxgui->leafmap) (0.2.2)
Collecting whitebox (from whiteboxgui->leafmap)
  Downloading whitebox-2.3.6-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (0.2.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->leafmap) (6.5.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (75.2.0)
Collecting jedi>=0.16 (from ipython>=4.0.0->ipywidgets->leafmap)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets->leafmap) (4.9.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.17.0)
Collecting backoff>=1.10.0 (from posthog>=3.0->ploomber-core>=0.2.7->jupysql)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.9.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.3->maplibre->leafmap) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.3->maplibre->leafmap) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.5.3->maplibre->leafmap) (0.4.2)
Requirement already satisfied: jsonschema~=4.18 in /usr/local/lib/python3.12/dist-packages (from pystac[validation]>=1.10.0->pystac-client->leafmap) (4.26.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium->leafmap) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium->leafmap) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->folium->leafmap) (2.5.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->leafmap) (6.5.7)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown->leafmap) (2.8.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown->leafmap) (1.7.1)
Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.12/dist-packages (from whitebox->whiteboxgui->leafmap) (8.3.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets->leafmap) (0.8.5)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac-client->leafmap) (0.30.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->leafmap) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->leafmap) (5.9.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (25.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (7.17.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.24.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.3.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets->leafmap) (0.7.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->leafmap) (4.5.1)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.2.4)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.21.2)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (25.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (1.4.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.14.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (3.0)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (4.12.1)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (0.5.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->leafmap) (7.7.0)

In [2]:
url = "https://s3.amazonaws.com/s3.cleverelephant.ca/postgis-workshop-2020.zip"
zip_path = "nyc_data.zip"
r = requests.get(url)
with open(zip_path, "wb") as f:
    f.write(r.content)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("nyc_data")

os.listdir("nyc_data")

['postgis-workshop']

In [3]:
os.listdir("nyc_data/postgis-workshop/data")

['nyc_homicides.prj',
 'nyc_streets.dbf',
 'nyc_homicides.shp',
 'nyc_streets.shp',
 'nyc_census_blocks.shx',
 'nyc_neighborhoods.shx',
 'nyc_census_blocks.dbf',
 'nyc_streets.shx',
 'nyc_subway_stations.shp',
 'nyc_neighborhoods.prj',
 'nyc_homicides.shx',
 'nyc_data.backup',
 'nyc_streets.prj',
 'nyc_subway_stations.shx',
 'nyc_census_blocks.shp',
 'nyc_subway_stations.dbf',
 'nyc_neighborhoods.shp',
 'nyc_subway_stations.prj',
 'nyc_homicides.dbf',
 'nyc_neighborhoods.dbf',
 'nyc_census_sociodata.sql',
 '2000',
 'nyc_census_blocks.prj']

In [4]:
con = duckdb.connect()
con.install_extension("httpfs")
con.load_extension("httpfs")
con.install_extension("spatial")
con.load_extension("spatial")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [5]:
tables = [
    "nyc_neighborhoods",
    "nyc_census_blocks",
    "nyc_homicides",
    "nyc_streets",
    "nyc_subway_stations"
]

for table in tables:
    shp_file = f"nyc_data/postgis-workshop/data/{table}.shp"
    con.execute(f"""
        CREATE TABLE {table} AS
        SELECT * FROM ST_Read('{shp_file}');
    """)

In [6]:
print(con.execute("SHOW TABLES;").fetchall())

[('nyc_census_blocks',), ('nyc_homicides',), ('nyc_neighborhoods',), ('nyc_streets',), ('nyc_subway_stations',)]

## Question 2:
How many subway stations are there in NYC?

In [7]:
con.sql("""
    SELECT COUNT(*)
    FROM nyc_subway_stations;
""")

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│          491 │
└──────────────┘

## Question 3:

What combination of borough and year hard the largest number of homicide victims?

In [8]:
con.sql("""
    SELECT *
    FROM nyc_homicides
    LIMIT 5;
""").df()

,INCIDENT_D,BORONAME,NUM_VICTIM,PRIMARY_MO,ID,WEAPON,LIGHT_DARK,YEAR,geom
0,2008-01-01,Brooklyn,1,None,7,gun,D,2008,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
1,2008-01-04,Manhattan,1,None,14,gun,D,2008,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
2,2008-01-05,Queens,1,None,15,gun,D,2008,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
3,2008-01-04,Queens,1,None,16,knife,D,2008,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
4,2008-01-05,Queens,1,None,18,gun,D,2008,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."

In [9]:
con.sql("""
    SELECT
        BORONAME,
        YEAR,
        SUM(CAST(NUM_VICTIM AS INTEGER)) AS total_victims
    FROM nyc_homicides
    GROUP BY BORONAME, YEAR
    ORDER BY total_victims DESC
    LIMIT 1;
""")

┌──────────┬───────┬───────────────┐
│ BORONAME │ YEAR  │ total_victims │
│ varchar  │ int64 │    int128     │
├──────────┼───────┼───────────────┤
│ Brooklyn │  2003 │           235 │
└──────────┴───────┴───────────────┘

## Question 4:

Which subway station has the largest number of shooting victims within a 300 meter radius?

In [10]:
con.sql("""
    SELECT
        s.name AS station_name,
        SUM(CAST(h.NUM_VICTIM AS INTEGER)) AS total_victims
    FROM nyc_subway_stations s
    JOIN nyc_homicides h
      ON ST_DWithin(
          s.geom,
          h.geom,
          300
      )
    WHERE h.WEAPON = 'gun'
    GROUP BY s.name
    ORDER BY total_victims DESC
    LIMIT 1;
""")

┌──────────────┬───────────────┐
│ station_name │ total_victims │
│   varchar    │    int128     │
├──────────────┼───────────────┤
│ Franklin Ave │            28 │
└──────────────┴───────────────┘

## Question 5

what is the most densely populated residential street in new york? (total population of intersecting census blocks divided by the total length of the street)

In [15]:
con.sql("""
    SELECT
        s.name AS street_name,
        SUM(CAST(c.popn_total AS INTEGER)) / ST_Length(s.geom) AS pop_density
    FROM nyc_streets s
    JOIN nyc_census_blocks c
      ON ST_Intersects(s.geom, c.geom)
    WHERE s.type = 'residential'
    GROUP BY s.name, s.geom
    HAVING ST_Length(ST_Union_Agg(s.geom)) > 0
    ORDER BY pop_density DESC
    LIMIT 1;
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  street_name  pop_density
0     W 66 St   3223.78748

# Section 2

This section uses internet speed data from [Ookla](https://github.com/teamookla/ookla-open-data); take a minute to read the documentation of the dataset.

Create a table called ookla_nyc which reads the data from this url:

https://storage.googleapis.com/qm2/CASA0025/ookla_nyc.parquet

In [13]:
con.sql("""
    CREATE TABLE ookla_nyc AS
    SELECT *
    FROM 'https://storage.googleapis.com/qm2/CASA0025/ookla_nyc.parquet';
""")

In [14]:
con.sql("SHOW TABLES;")

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ nyc_census_blocks   │
│ nyc_homicides       │
│ nyc_neighborhoods   │
│ nyc_streets         │
│ nyc_subway_stations │
│ ookla_nyc           │
└─────────────────────┘

In [18]:
con.sql("SELECT * FROM ookla_nyc LIMIT 5;").df()

,quadkey,tile_x,tile_y,avg_d_kbps,avg_u_kbps,avg_lat_ms,avg_lat_down_ms,avg_lat_up_ms,tests,devices,quarter,type,year,geometry
0,0320101100103011,-74.2923,40.9446,725128,135953,11,57,216,6,3,3,fixed,2025,"POLYGON ((559335.820448 4533081.030772, 559798..."
1,0320101100103100,-74.2868,40.9446,119511,14121,12,814,210,7,1,3,fixed,2025,"POLYGON ((559798.18087 4533084.773678, 560260...."
2,0320101100103101,-74.2813,40.9446,239400,33087,19,123,86,2,2,3,fixed,2025,"POLYGON ((560260.541371 4533088.54564, 560722...."
3,0320101100103103,-74.2813,40.9405,351406,314161,3,12,26,1,1,3,fixed,2025,"POLYGON ((560264.313317 4532627.94173, 560726...."
4,0320101100103110,-74.2758,40.9446,327591,153403,6,315,155,5,3,3,fixed,2025,"POLYGON ((560722.90195 4533092.346658, 561185...."

## Question 6
How many tiles are contained within new york city neighbourhoods?

In [21]:
con.sql("""
    SELECT COUNT(DISTINCT o.quadkey) AS num_tiles
    FROM ookla_nyc o
    JOIN nyc_neighborhoods n
      ON ST_Within(
           ST_GeomFromText(o.geometry),
           n.geom
         );
""")

┌───────────┐
│ num_tiles │
│   int64   │
├───────────┤
│      1403 │
└───────────┘

## Question 7

Which neighbourhood has the highest average download speed? use 'within' rather than intersects, and ignore tiles with fewer than 3 tests.

In [22]:
con.sql("""
    SELECT
        n.name AS neighbourhood,
        AVG(o.avg_d_kbps) / 1000.0 AS avg_download_mbps
    FROM ookla_nyc o
    JOIN nyc_neighborhoods n
      ON ST_Within(
           ST_GeomFromText(o.geometry),
           n.geom
         )
    WHERE o.tests >= 3
    GROUP BY n.name
    ORDER BY avg_download_mbps DESC
    LIMIT 1;
""")

┌───────────────┬───────────────────┐
│ neighbourhood │ avg_download_mbps │
│    varchar    │      double       │
├───────────────┼───────────────────┤
│ Woodside      │ 455.9603333333333 │
└───────────────┴───────────────────┘

## Question 8

What is the name of the subway station closest to the tile with the highest download speed?

In [23]:
con.sql("""
    WITH fastest_tile AS (
        SELECT
            ST_GeomFromText(geometry) AS geom
        FROM ookla_nyc
        ORDER BY avg_d_kbps DESC
        LIMIT 1
    )
    SELECT
        s.name AS station_name
    FROM nyc_subway_stations s, fastest_tile f
    ORDER BY ST_Distance(s.geom, f.geom) ASC
    LIMIT 1;
""")

┌──────────────┐
│ station_name │
│   varchar    │
├──────────────┤
│ 190th St     │
└──────────────┘

## Question 9

Which neighbourhood has the highest number of devices per capita? Use only spatial intersections.

In [24]:
con.sql("""
    SELECT
        n.name AS neighbourhood,
        SUM(o.devices) * 1.0 / SUM(c.popn_total) AS devices_per_capita
    FROM nyc_neighborhoods n
    JOIN ookla_nyc o
      ON ST_Intersects(
          ST_GeomFromText(o.geometry),
          n.geom
      )
    JOIN nyc_census_blocks c
      ON ST_Intersects(c.geom, n.geom)
    GROUP BY n.name
    ORDER BY devices_per_capita DESC
    LIMIT 1;
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌───────────────┬────────────────────┐
│ neighbourhood │ devices_per_capita │
│    varchar    │       double       │
├───────────────┼────────────────────┤
│ Flatbush      │                inf │
└───────────────┴────────────────────┘

## Question 10

What is the average upload speed for tiles that are within 200 meters of L train stops and intersect with census blocks where the black population is above 50%?

In [26]:
con.sql("""
    SELECT
        AVG(o.avg_u_kbps) AS avg_upload_speed_kbps
    FROM ookla_nyc o
    JOIN nyc_subway_stations s
      ON ST_DWithin(
          ST_GeomFromText(o.geometry),
          s.geom,
          200
      )
    JOIN nyc_census_blocks c
      ON ST_Intersects(
          ST_GeomFromText(o.geometry),
          c.geom
      )
    WHERE s.ROUTES LIKE '%L%'
      AND c.popn_black * 1.0 / c.popn_total > 0.5;
""")

┌───────────────────────┐
│ avg_upload_speed_kbps │
│        double         │
├───────────────────────┤
│    124413.30695443646 │
└───────────────────────┘